### ISSUE TITLE
yarn build failed!!!

### ISSUE THREAD

**Issue by struckchure** [Horlakz/Horlakz#1]
```bash
$ yarn build
Could not resolve './src/assets/fonts/icon.css' from index.html
error during build:
Error: Could not resolve './src/assets/fonts/icon.css' from index.html
    at error (/home/mohammed/Documents/Contributions/Horlakz/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.handleResolveId (/home/mohammed/Documents/Contributions/Horlakz/node_modules/rollup/dist/shared/rollup.js:22379:24)
    at /home/mohammed/Documents/Contributions/Horlakz/node_modules/rollup/dist/shared/rollup.js:22358:2
```

**Comment by horlakz** [comment]
Fixed sir
